colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
replyByEmail = true
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
defaultBackgroundImage = "ic410background"
#defaultFeaturedImage = "avatar.jpg"  #if this is set, it is used on homepage as feature image for each article, 
#                                      but is NOT used as background image on article page
disableImageZoom = true  # the default is false, which enables user to click on any image to zoom it

[header]
layout = "fixed-fill-blur"   # supported values are basic, fixed, fixed-fill, and fixed-fill-blur
# with basic, the header is attached to the page and scrolls up and off the screen
# with fixed, it stays in place but dark things on the page obscure it
# with fixed-fill it stays but with white background and page does not obscure it
# with fixed-fill-blurit starts with same background as page but turns white as page scrolls up

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"  # Valid values are page, profile, hero, card, background, or custom. 
showRecent = true
showRecentItems = "6"
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "ic410background.jpg"

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = false
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = true
showReadingTime = true
showTableOfContents = false
showTaxonomies = true
showAuthorsBadges = false
showWordCount = true
showZenMode = true
#sharingLinks = [ "email", "twitter","facebook","telegram"]

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = true

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]

[rssnext]



